export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/product/list/index',
    'pages/product/detail/index',
    'pages/cart/index',
    'pages/order/create/index',
    'pages/order/list/index',
    'pages/order/detail/index',
    'pages/payment/index',
    'pages/customization/index',
    'pages/after-sales/apply/index',
    'pages/reviews/index',
    'pages/profile/index',
    'pages/profile/alumni-verify/index',
    'pages/address/list/index',
    'pages/address/edit/index',
    'pages/notifications/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '校庆纪念品',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#999',
    selectedColor: '#1989fa',
    backgroundColor: '#fff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tabs/home.png',
        selectedIconPath: 'assets/tabs/home-active.png',
      },
      {
        pagePath: 'pages/product/list/index',
        text: '商品',
        iconPath: 'assets/tabs/shop.png',
        selectedIconPath: 'assets/tabs/shop-active.png',
      },
      {
        pagePath: 'pages/cart/index',
        text: '购物车',
        iconPath: 'assets/tabs/cart.png',
        selectedIconPath: 'assets/tabs/cart-active.png',
      },
      {
        pagePath: 'pages/order/list/index',
        text: '订单',
        iconPath: 'assets/tabs/order.png',
        selectedIconPath: 'assets/tabs/order-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tabs/user.png',
        selectedIconPath: 'assets/tabs/user-active.png',
      },
    ],
  },
})
